<?php /** @var $block \Monashee\Recaptcha\Block\Recaptcha */ ?>
<?php if ($block->isEnabled()): ?>
    <script type="text/javascript" src="https://www.google.com/recaptcha/api.js"></script>
    <div class="g-recaptcha" data-sitekey="<?php echo $block->getSiteKey();?>" data-callback="onReCaptchaSuccess"></div>
    <script type="text/javascript">
    //<![CDATA[
    var onReCaptchaSuccess = function() {
        if (window.innerWidth < 768 && (/iPhone|iPod/.test(navigator.userAgent) && !window.MSStream)) {
            jQuery('body, html').animate({scrollTop: jQuery('.g-recaptcha').offset().top}, 'slow');
        }
    }
    //]]>
    </script>
<?php endif; ?>
