<?php /** @var $block \Monashee\Recaptcha\Block\Recaptcha */ ?>
<?php if ($block->isEnabled()): ?>
    <script type="text/javascript" src="https://www.google.com/recaptcha/api.js"></script>
    <div class="g-recaptcha" data-sitekey="<?php echo $block->getSiteKey();?>" data-callback="onReCaptchaSuccess"></div>
    <script type="text/javascript">
    //<![CDATA[
    require(
        ['jquery'],
        function(jQuery){
            jQuery(document).ready(function(){
                var onReCaptchaSuccess = function() {
                    if (window.innerWidth < 768 && (/iPhone|iPod/.test(navigator.userAgent) && !window.MSStream)) {
                        var destElementOffset = jQuery('.g-recaptcha').position().top - window.innerWidth;
                        jQuery('html, body').animate({ scrollTop: destElementOffset }, 0);
                    }
                }
            });
        }
    );
    //]]>
    </script>
<?php endif; ?>
